name: Self-Hosted Runner CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{matrix.node.version }}
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can change this to the required Node version

      - name: Install dependencies
        run: |
          npm install  # Install dependencies using npm (for Node.js)

      - name: Run tests
        run: |
          npm test  # Run your tests using npm (assuming you have test scripts set in package.json)
